#!/bin/sh

# This script checks that the commit message is greater than 3 characters.

commit_msg=$(cat "$1")
min_length=3

# Check if commit message length is greater than 3 characters
if [ ${#commit_msg} -le $min_length ]; then
  echo "Error: Commit message must be longer than 3 characters."
  exit 1
fi


# Allow the commit if the message is valid
exit 0

